apiVersion: batch/v1
kind: Job
metadata:
  name: console-post-upgrade
  namespace: "services"
  annotations:
    "helm.sh/hook": "post-upgrade"
spec:
  template:
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      containers:
      - name: hook1-container
        image: {{ .Values.alpine.image.repository }}:{{ .Values.alpine.image.tag }}
        imagePullPolicy: {{ .Values.alpine.image.pullPolicy }}
        command: ['sh', '-c', 'mkdir -p /var/log/conman /var/log/conman.old /var/log/console && chown -Rv 65534:65534 /var/log && chmod -R 700 /var/log']
        volumeMounts:
          - mountPath: /var/log
            name: cray-console-logs
      volumes:
        - name: cray-console-logs
          persistentVolumeClaim:
            claimName: cray-console-operator-data-claim
